---
title: "HW3"
author: "Aaron"
date: "2/2/2018"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

###Problem1
```{r}
a <- c(1:10)
b <- c(0:9) 
paste("c_{",a,"}X_{",a,"}^",b,sep="",collapse = "+")
```

###Problem2-1
```{r}
ptm <- proc.time()
sample_space <- c(rep("Y",3),rep("B",7))
n <- 1000000
acc <- 0
for (i in 1:n) {
  if (sum(sample(sample_space, 3) == "Y") == 1) {
    acc = acc + 1
  }
}
acc/n
proc.time() - ptm
```

###Problem2-2
```{r}
ptm <- proc.time()
acc <- 0
for (i in 1:n) {
  acc = acc + ifelse(sum(sample(sample_space, 3) == "Y") == 1,1,0)
}
acc/n
proc.time() - ptm
```


###Problem2-3
```{r}
ptm <- proc.time()
sum(sapply(1:n, function(x) sum(sample(sample_space, 3) == "Y") == 1))/n
proc.time() - ptm
```

The rank from the fastest to slowest: 1 -> 3 -> 2.

###Problem3-1
```{r}
sum(sapply(1:n, function(x) sum(sample(sample_space, 3) == "Y") <= 1))/n
```

###Problem3-2
```{r}
sum(sapply(1:n, function(x) sum(sample(sample_space, 3) == "Y") >= 1))/n
```

###Problem4
```{r}
open.account <- function(total, name) {
  n.dep <- 1
  n.withdrawal <- 0
  cat("Balance (",name,"): ", total, ". You made ", n.dep, " deposits and ", 
      n.withdrawal,   " withdrawals.", sep = "")
  
  deposit <- function(amount) {
    if(amount <= 0)
      stop("Deposits must be positive!\n")
    total <<- total + amount
    n.dep <<- n.dep + 1
    cat(amount, " deposited. ", sep = "")
    balance()
  }
  
  withdraw <- function(amount) {
    if(amount <= 0)
      stop("Withdraw must be positive!\n")
    total <<- total - amount
    n.withdrawal <<- n.withdrawal + 1
    cat(amount, " withdrawn. ", sep = "")
    balance()
  }
  
  transfer <- function(amount, whom) {
    if(amount <= 0)
      stop("Transfering money must be positive!\n")
    if((total - amount) <= 0)
      stop("No enough money in deposits!\n")
    withdraw(amount)
    whom$deposit(amount)
  }
  
  balance <- function() {
    cat("Balance (",name,"): ", total, ". You made ", n.dep, " deposits and ",
        n.withdrawal, " withdrawals.\n", sep = "")
  }
  
  list(deposit = deposit,
       withdraw = withdraw,
       balance = balance,
       transfer = transfer)
  
}
```

```{r}
lily <- open.account(200, "Lily")
```

```{r}
ross <- open.account(100, "Ross")
```

```{r}
lily$transfer(70,ross)
```

```{r}
ross$withdraw(50)
```

```{r}
lily$deposit(30)
```

```{r}
ross$transfer(100,lily)
```

```{r}
lily$balance()
```

```{r}
ross$balance()
```

###Problem5
```{r}
par(mar=c(2, 2, 2, 1), mgp=c(1.1, 0.15, 0), tck=-0.01)
a <- rnorm(500) 
layout(mat=matrix(c(2,2,2,
                    2,2,2,
                    2,2,2,
                    1,1,3,
                    1,1,3),nrow = 5,byrow=TRUE))
plot(a) 
hist(a) 
boxplot(a)
```

###Problem6
```{r}
CIS <- function(n, conf.coeff, real.mu, real.var, B) {

  real.sd <- sqrt(real.var)
  s <- matrix(sapply(1:B, function(x) rnorm (n,real.mu,real.sd)),ncol = B)
  x <- colMeans(s)


  if (conf.coeff == 0.68) dev <- 1
  if (conf.coeff == 0.95) dev <- 1.96
  if (conf.coeff == 0.99) dev <- 3

  CIlow <- x - dev*real.sd/sqrt(n)
  CIhigh <- x + dev*real.sd/sqrt(n)

  a <- CIlow <= real.mu & CIhigh >= real.mu
  y <- 1:B

  plot(x, y, xlab = "True mean (in blue) and CIs", ylab = "cases",
       xlim = c(7,13), ylim =c(0,100), 
       main = paste("[successful CIs:", sum(a),"%]"), col = ifelse(a,"darkgreen","red"))
  abline(v = 10, lwd = 3, col = "blue", lty = 'dashed')
  segments(CIlow, y, CIhigh, y, col = ifelse(a, "darkgreen", "red"), lwd = 1)
}

CIS(10, 0.95, 10, 4, 100)
```



