---
title: "Project"
author: "Aaron"
date: "3/25/2018"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(plyr)
library(dplyr)
library(magrittr)
library(reshape2)
library(ggplot2)
library(lubridate) 

a <- read.csv(file="/Users/aaron/Desktop/R/Project/TrafficCollision.csv", header=TRUE, sep=",")
b <- read.csv(file="/Users/aaron/Desktop/R/Project/QuickFacts-Mar-25-2018.csv", header=TRUE, sep=",")
```

```{r}
Male <- subset(count(a, Victim.Sex, Date.Occurred), Victim.Sex == "M")
Female <- subset(count(a, Victim.Sex, Date.Occurred), Victim.Sex == "F")
num <- inner_join(Male, Female, by = "Date.Occurred")

d <- data_frame(date = as.Date(num$Date.Occurred, format = "%m/%d/%Y"),
                Number.of.Male = num$n.x,
                Number.of.Femlae = num$n.y)

dmelt <- subset(melt(d, id.vars = "date", variable.name = "type"), date != "2018-03-17" & date != "2018-03-16")

ggplot(dmelt)+
aes(date, value, colour = type)+
geom_line()+
theme(
  plot.title = element_text(size = 13, hjust = 0.5, face = "bold"),
  axis.title = element_text(size = 12, face = "bold"),
  strip.text.x = element_text(size = 12, face = "bold"),
  legend.title = element_text(size = 8),
  legend.key.size = unit(0.5, "cm"),
  legend.text = element_text(size = 6)
)+
labs(
  x = "Date",
  y = "Number of Incidents Per Day",
  shape = "Transmission"
)+
scale_colour_manual(
  values = c("darkblue", "orange"),
  name = "Gender",
  labels = c("Male", "Female")
)+
ggtitle("Time Series Plot of Traffic Collision Incidents from 2010")


```

```{r}
a %>%
  filter(Victim.Descent!="" & Victim.Descent!="-") %>%
  group_by(Victim.Descent) %>%
  summarise(n = n()) %>%
  ggplot() +
  aes(x=reorder(Victim.Descent,-n), y = n) +
  geom_bar(stat = "identity") 
  
```

```{r}
youth<-within(filter(a, a$Victim.Age <= 30),{Time<- floor(Time.Occurred/100)})
youth1<-count(youth, Time)

strong<-within(filter(a, Victim.Age > 30 & Victim.Age < 60),{Time<- floor(Time.Occurred/100)})
strong1<-count(strong, Time)

old <-within(filter(a, Victim.Age >= 60),{Time<- floor(Time.Occurred/100)})
old1<-count(old, Time)

AGEH<-data.frame(Time = youth1$Time,
                 Youth.Number = youth1$n,
                 Strong.Number = strong1$n,
                 Old.Nimber = old1$n)
MAGEH <- melt (AGEH, id.vars = "Time", variable.name = "age")
ggplot(MAGEH) +
aes(Time, value, colour = age) +  
geom_line()+
scale_colour_manual(values = c("darkblue","red","darkgreen"))
```

```{r}
TCS<- filter(a, Victim.Sex !="" , Victim.Sex != "H", Victim.Sex !="X" )
h<-hour(as.POSIXct(sprintf("%04.0f", TCS$Time.Occurred), format="%H%M"))
##Bar graph
ggplot(TCS, aes(h, fill = Victim.Sex))+ geom_bar()
```
